### ISSUE TITLE
Not Go Gettable

### ISSUE THREAD

**Issue by rauljordan** [moonfruit/bls#1]
Hi Moonfruit,

Tried doing a go get with the project and got the error:

```bash
go get github.com/moonfruit/bls 
# github.com/moonfruit/bls
/usr/bin/ld:/home/me/Desktop/Go/src/github.com/moonfruit/bls/lib/linux/amd64/libbls384.a: file format not recognized; treating as linker script
/usr/bin/ld:/home/me/Desktop/Go/src/github.com/moonfruit/bls/lib/linux/amd64/libbls384.a:1: syntax error
```

I am also doing this similar effort in my repo: https://github.com/prysmaticlabs/go-bls so I understand the struggle of getting all these pieces to work. Do you know how we could fix this issue?

**Comment by moonfruit** [comment]
That might be I used git-lfs to upload the precompiled libs. I will dig for some solutions.

**Comment by moonfruit** [comment]
Yes, I confirmed that is about git-lfs.

I used git-lfs to managed the libs, so, if you want `go get` this lib, you must install [git-lfs](https://git-lfs.github.com/) first.
